server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://localhost:5435/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



#management:
#  endpoint:
#    health:
#      show-details: "ALWAYS"
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  context-path: http://localhost:${server.port}/actuator
#
#
#info:
#  application:
#    name: ${spring.application.name}
#    description: Ticketing Application
#    version: '@project.version@'
#    spring-cloud-version: '@spring-cloud.version@'
#    spring-boot-version: '@project.parent.version@'
#
#
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        permittedNumberOfCallsInHalfOpenState: 2
#        slidingWindowSize: 2
#        waitDurationInOpenState: 10000
#        slidingWindowType: COUNT_BASED
#    instances:
#      user-service:
#        baseConfig: default
#        waitDurationInOpenState: 15000
#      task-service:
#        baseConfig: default
#        waitDurationInOpenState: 20000
#  retry:
#    configs:
#      default:
#        maxAttempts: 3
#        waitDuration: 200
#    instances:
#      user-service:
#        baseConfig: default
#  ratelimiter:
#    instances:
#      test:
#        timeout-duration: 5000
#        limitRefreshPeriod: 5000
#        limitForPeriod: 1